{
 "title": "CrowdSec Cyber Threat Insights",
 "description": "Cyber threat insights with Crowdsec, VictoriaMetrics and Grafana",
 "tags": [
  "cyberthreat",
  "crowdsec"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(cs_lapi_decision,instance)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Cyberthreats Over Last Month / Granularity: 1m",
   "type": "table",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (instance,country,asname,asnumber,iprange,ip,type) (count_over_time(cs_lapi_decision{instance=~\"${host:raw}\"}[30d:1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 Cyberthreat Countries",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (country) (count_over_time(cs_lapi_decision{instance=~\"${host:raw}\"}[30d:1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cyberthreats Map",
   "type": "geomap",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum by(country,longitude,latitude) (count_over_time(cs_lapi_decision{instance=~\"${host:raw}\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Realtime Cyberthreats: ${__from:date:YYYY-MM-DD HH:mm:ss} - ${__to:date:YYYY-MM-DD HH:mm:ss} / Granularity: $__interval",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cs_lapi_decision{instance=~\"${host:raw}\"}[$__range:$__interval]",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}